"""Build review-only secondary pages with the homepage's shared navigation/footer."""
from pathlib import Path

root = Path(__file__).resolve().parent
home = (root / 'design-preview.html').read_text(encoding='utf-8')
head = home.split('<main id="main">')[0]
foot = home.split('</main>')[1]
head = head.replace('href="#features"', 'href="design-preview.html#features"').replace('href="#community"', 'href="design-preview.html#community"')

pages = {
    'demos-preview.html': '''
<div class="wrap"><div class="page-heading"><p class="eyebrow">See what is possible</p><h1>Ideas for your everyday.</h1><p>Short demos. Real workflows. Find something useful and make it your own.</p></div>
<nav class="topic-nav" aria-label="Demo topics"><a href="#all" aria-current="page">All demos</a><a href="#workflow">Launch & control</a><a href="#home">Dashboards & home</a><a href="#media">Everyday apps</a><a href="#customize">Customize & extend</a></nav>
<section class="featured-demo" id="all"><div class="poster"><img src="../shots/editor-default.png" width="1164" height="701" alt="Earlier desktop editor showing a launcher page"><span class="pending">Existing screenshot · overview footage planned</span></div><div><p class="eyebrow">Start here</p><h2>Your tools, together.</h2><p class="muted">See how pages, apps, and dashboards fit into a workspace that is yours to arrange.</p><a class="textlink" href="docs-preview.html">Explore the getting-started guide →</a></div></section>
<section class="demo-grid" aria-label="Demo library"><article class="demo-card" id="workflow"><div class="poster"><img src="../shots/editor-default.png" width="1164" height="701" alt="Launcher grid" loading="lazy"><span class="pending">Screenshot · footage planned</span></div><span class="tag">Launch & control</span><h3>Launch a workflow.</h3><p>Bring your daily apps and actions into one place.</p><a class="textlink" href="docs-preview.html#pages">See the setup →</a></article>
<article class="demo-card" id="home"><div class="poster portrait"><div class="portrait-slate"><span>PORTRAIT DEMO</span><strong>Control<br>a room.</strong><span>9:16 footage slot</span></div><span class="pending">Design placeholder</span></div><span class="tag">Dashboards & smart home</span><h3>Put your home in reach.</h3><p>Home Assistant and dashboards on your control surface.</p><a class="textlink" href="docs-preview.html#integrations">See the setup →</a></article>
<article class="demo-card" id="media"><div class="poster"><img src="../shots/editor-media.png" width="1164" height="701" alt="Media shortcuts" loading="lazy"><span class="pending">Screenshot · footage planned</span></div><span class="tag">Everyday apps</span><h3>Manage your media.</h3><p>Make a page for the things you listen to and watch.</p><a class="textlink" href="docs-preview.html#apps">See the setup →</a></article></section>
<div class="notice" id="customize">Review note: this library shows the media layout before final footage is available. Published demos get their own page, actual duration, captions/transcript, and related setup links. Topic links become WordPress tag archives.</div>
<section class="section"><div class="section-head"><div><p class="eyebrow">Have a setup worth sharing?</p><h2>Show us what you made.</h2></div><a class="button" href="https://discord.gg/7F8DFMVQMv">Share on Discord ↗</a></div></section></div>
''',
    'docs-preview.html': '''
<div class="wrap"><div class="page-heading"><p class="breadcrumbs"><a href="design-preview.html">Home</a> / Documentation</p><h1>A good place to start.</h1><p>Set up Bedrock Panel, make your first page, and explore what comes next.</p></div>
<details class="doc-mobile"><summary>Browse documentation</summary><nav aria-label="Documentation topics"><a href="#start">Getting started</a><a href="#pages">Pages & layouts</a><a href="#apps">Apps & integrations</a><a href="#hardware">Devices & hardware</a><a href="#help">Troubleshooting</a></nav></details>
<div class="doc-layout"><aside class="doc-nav" aria-label="Documentation"><strong>Getting started</strong><a href="#start">Overview</a><a href="download-preview.html">Installation</a><a href="#pages">Your first page</a><strong>Make it yours</strong><a href="#pages">Pages & layouts</a><a href="#apps">Apps</a><a href="#integrations">Integrations</a><a href="#hardware">Devices & hardware</a><strong>Get help</strong><a href="#help">Troubleshooting</a><a href="https://github.com/TeeJS/bedrock-panel">Development ↗</a></aside>
<article class="doc-content" id="start"><h2>Your setup starts with software.</h2><p class="lead">Run on a compatible Windows PC, then choose the apps, actions, and dashboards you want nearby. A touchscreen or knob is optional.</p><ol class="steps"><li><div><h3>Download the current release.</h3><p>Choose a Windows package from the <a href="download-preview.html">download page</a>.</p></div></li><li><div><h3>Choose your setup.</h3><p>Start with a desktop window or follow the guide for your compatible display.</p></div></li><li><div><h3>Create a page.</h3><p>Use the editor to arrange a grid, add an app, or display a web dashboard.</p></div></li></ol>
<div class="doc-topics"><section class="doc-topic" id="pages"><h3>Pages & layouts</h3><p>Grids, dashboard pages, software panes, and the desktop editor.</p><a class="textlink" href="https://github.com/TeeJS/bedrock-panel/tree/main/docs">Read project guides ↗</a></section><section class="doc-topic" id="apps"><h3>Apps for your day</h3><p>Media, clocks, system information, meetings, dictation, and translation.</p><a class="textlink" href="https://github.com/TeeJS/bedrock-panel/tree/main/docs">Browse app guides ↗</a></section><section class="doc-topic" id="integrations"><h3>Connect your tools</h3><p>Home Assistant, web dashboards, and connected services.</p><a class="textlink" href="https://github.com/TeeJS/bedrock-panel/tree/main/docs">Explore integrations ↗</a></section><section class="doc-topic" id="hardware"><h3>Devices & hardware</h3><p>Compatible screens, optional controllers, and the DIY Bedrock Console.</p><a class="textlink" href="https://github.com/TeeJS/bedrock-console-hardware">Explore console guides ↗</a></section></div>
<section id="help"><h3>Need a hand?</h3><p>Bring your setup and question to <a href="https://discord.gg/7F8DFMVQMv">Discord</a>. For a reproducible software issue, use the project’s <a href="https://github.com/TeeJS/bedrock-panel/issues">issue tracker</a>.</p></section>
<div class="notice">Design review: topic pages will be integrated WordPress documentation. Current links point to existing source guides until that content is migrated and reviewed.</div>
</article></div></div>
''',
    'download-preview.html': '''
<div class="wrap"><div class="page-heading"><p class="eyebrow">Make a space that works for you</p><h1>Get Bedrock Panel.</h1><p>Start on your desktop. Add a compatible touchscreen or build a Bedrock Console when you are ready.</p></div>
<div class="download-grid"><section class="download-box"><p class="eyebrow">Windows</p><h2>Your controls start here.</h2><p>Get the current package from the project’s GitHub releases. Check the release notes for the latest fixes and requirements.</p><div class="actions"><a class="button" href="https://github.com/TeeJS/bedrock-panel/releases">View Windows releases ↗</a></div><div class="release-options"><article><h3>Installer</h3><p>Choose the setup package when it is included in the current release. Follow its installation steps.</p></article><article><h3>Portable package</h3><p>Choose the portable executable when it is included in the current release. No package filename is assumed here.</p></article></div><p class="small">Design note: the live page will show the verified release version, date, and exact download links. These values belong in editable content, not the theme.</p></section>
<aside class="download-aside"><h2>A few things to know.</h2><h3>No dedicated hardware required.</h3><p>Software mode runs in a desktop window on a compatible Windows PC.</p><h3>Using a touchscreen?</h3><p>Check its layout and input setup in the <a href="docs-preview.html#hardware">hardware guides</a>. A 1920×480 canvas is the starting point for panel pages; supported configurations need to be checked for your setup.</p><h3>Building your own?</h3><p>The <a href="https://github.com/TeeJS/bedrock-console-hardware">Bedrock Console</a> is a DIY touchscreen build with an optional knob.</p><h3>Read before updating.</h3><p>Review the <a href="https://github.com/TeeJS/bedrock-panel/releases">release notes</a> and setup guidance for the package you choose.</p></aside></div></div>
<section class="section white"><div class="wrap start-grid"><div><p class="eyebrow">Next up</p><h2>Make your first page.</h2><p class="lead">Start with the apps and actions you use every day.</p></div><div><a class="button" href="docs-preview.html">Open the getting-started guide →</a><p class="muted small" style="margin-top:24px">Questions along the way? <a href="https://discord.gg/7F8DFMVQMv">Join the community on Discord.</a></p></div></div></section>
'''
}
for name, content in pages.items():
    (root / name).write_text(head + '<main id="main">' + content + '</main>' + foot, encoding='utf-8')
print('Built ' + ', '.join(pages))
